Milestone 3: Added a Contact-Form to the Portfolio
Chandan-devs-tech/Demo2 pull request #4
Opened 2023-01-21 01:58 UTC by Chandan-devs-tech

# Project Requirements

## In this section I have to build a:
- The contact form
-  and the footer (if present in the design)
- These Instructions are to be followed in the Form:
  - Name field accepts up to 30 chars.
  - Email field accepts only emails.
  - Message field accepts up to 500 chars.
  - All fields have placeholder text.
  - All fields have the correct type.
  - A user cannot submit the form if one or more fields are empty.
- Collect data by using the [Formspree service](https://formspree.io/html).
- In order to lay out the elements on the page I should use Flexbox.
- I don't need to implement any functionality that requires JavaScript.
- I must stick to the design as much as possible (e.g., font, colors, images, text, margins) using [the templates in Figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1).
- Implementing the button interactions (enable, hover, etc.).

2023-01-21 02:43 UTC, AlphaNtihinduka requested changes
## Hi @Chandan-devs-tech 🙋‍♂️
Good job working on your first contact form. You have done the design to the best expectation and incredibly well. 👏  

However, there are some issues mostly with the UI design. 

You still need to implement a few on the project but you are almost there!!! :watch: 

TO HIGHLIGHT:
- Your project is professional ✅
- Professional README file :100: 
- Your PR is professional ✅
- Well-structured files ✅

# STATUS: Required Changes :recycle: 

![close](https://user-images.githubusercontent.com/99394374/210771148-619a4265-33b2-4e68-8901-6bb52693d6de.gif)
 ## Required Changes ♻️ 
- Kindly consider the inline comments. By applying them, your contact form will look professional.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread or slack channel if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

HAPPY CODING AND GOOD LUCK :crossed_fingers: :four_leaf_clover:

2023-01-21 02:43 UTC, AlphaNtihinduka commented on style.css
> +}
- [ ] The `border-radius` you have used looks nice and professional 👏  💯 . However, since we are supposed to stick to the [Figma template design](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=34%3A848&t=gtuHoeE75DvdApre-0), I suggest reducing the `border-radius` to match the template. 👍

2023-01-21 02:43 UTC, AlphaNtihinduka commented on style.css
> +}
- [ ] The `border-radius` you have used looks nice and professional 👏  💯 . However, since we are supposed to stick to the [Figma template design](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=34%3A848&t=gtuHoeE75DvdApre-0), I suggest reducing the `border-radius` to match the template. 👍

2023-01-21 02:43 UTC, AlphaNtihinduka commented on index.html
> +          </form>
- [ ] - [ ] The `Get In Touch` button you have used looks nice and professional 👏  💯 . However, since we are supposed to stick to the [Figma template design](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=34%3A848&t=gtuHoeE75DvdApre-0), I suggest centering the button instead of having it aligned to the left. 👍

2023-01-21 02:43 UTC, AlphaNtihinduka commented on style.css
> +}
- [ ] I have noticed that the `color` used on hover is not part of the Figma template design. This makes the design unprofessional 😞 . Kindly ensure that the color used matches the Figma design. This will give a better UI experience. 👌

2023-01-21 09:08 UTC, GedeonTS approved these changes
# STATUS: APPROVED :tada: :clap: :champagne: 
Hi @Chandan-devs-tech ,

You are amazing :smiley: :clap: !  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media.giphy.com/media/BPJmthQ3YRwD6QqcVD/giphy.gif"> 

## Highlights :clap: :tophat: 
- [x] Good README file :+1: 
- [x] No linter errors :+1: 
- [x] Good use of Github flow :+1: 
## Optional suggestions :small_airplane: 

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-21 09:08 UTC, GedeonTS commented on index.html
> +              <button type="button" class="form-btn">Get In Touch</button>
- [OPTIONAL ] Good job making the changes suggested by the previous reviewer :clap: , kindly make sure your form is submitting, for that you have to change the type into "submit" or remove it completely :recycle: 

__Please note that this requirement is only optional because the previous reviewer didn't mention it, but it's core for this milestone__

2023-01-21 17:48 UTC, merged

2023-01-25 16:30 UTC, mukhammadrizooff reviewed
Hi @Chandan-devs-tech, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media4.giphy.com/media/YKdm91XONLTaw/giphy-downsized-medium.gif"/>

## Highlights
- Good implementations ✔️ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._